language: haskell
ghc:
  - '8.6'
  - '8.4'
jobs:
  include:
    - stage: deploy
      if: tag =~ ^v[\d\.]+$
      script: skip
      deploy:
        provider: hackage
        username: mtth
        password:
          secure: a7u1UqFQeFT+L94FoPlAt1ZGGto1/fiwZRlJ3WKVhgXB3W+9fex14/UGFjbbonRYKJx+GWZekgxo6uGpnq3rRypMUcAnMoKR5QkDC9czMkr2kPlP/WTNTxHNByRy++zhaHs15crRUAuqySIiQ8ACFhmvgh5rVtbzGdlXmfRVD0DQWDt4b+04gskGbHOHf9S6PW0t/QWe8xh3/pE87P128ITopWzdOByYoDFo396g98mMl+3qPJ0LKpImvAJKkCXiNwQH7JJeIGttlMmYutzIDCCC4u7TbRSI+R7taM6FVtvBAeYvnRXo0zYPtZYEublJWCJAsAO8GelxHtnpqigP1gCLZS67iqvC4LlGIJDcIXWdTif83Ak5q8GPDGtmYjincGMWzE+ZWqSYYwq3lJ5QALqRKb9wlRwTnLTAZek5ttOGphRVGgx5ButmCm/BoUUB5hQ8bXUvMZ5+Z1rr0tR+GG8VT8cfSpFf3fuMxB1tq74/JJmO4Q35eWBCivY89XqArwf/r1lEctCvSl2FdNkjrSg+YVZUrwsS52ZBlvJpywylzipi1bO3xXWN7GZeP5LE3aZyjJ5WlU6YkU9jcNMbEr9ljYgft1GZK0mdOdiamEurtaf4usuTspG9uN5ZY5PPFHHjnrtylqE0nezY1IM41YV604/YhNvl7owrt1mzRcY=
        on:
          repo: mtth/more-containers
          tags: true
